[package]
name = "use-geologic-process"
description = "Primitive geologic process vocabulary for RustUse"
publish = true
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "README.md"
rust-version.workspace = true
documentation = "https://docs.rs/use-geologic-process"
keywords = ["geologic-process", "geology", "earth", "process", "rustuse"]
categories = ["data-structures", "science"]

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true
