[package]
name = "use-rock"
description = "Primitive rock vocabulary for RustUse"
publish = true
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "README.md"
rust-version.workspace = true
documentation = "https://docs.rs/use-rock"
keywords = ["rock", "geology", "earth", "classification", "rustuse"]
categories = ["data-structures", "science"]

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true
